# Generated by Django 2.1.7 on 2020-11-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_person_name', models.CharField(default='Unavailable', max_length=100)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('address', models.CharField(default='Unavailable', max_length=100)),
                ('source', models.CharField(default='Unavailable', max_length=100)),
                ('current_stage', models.CharField(default='Unavailable', max_length=100)),
                ('date_of_followup', models.DateField()),
                ('response', models.CharField(max_length=100)),
                ('medium_used', models.CharField(choices=[('call', 'call'), ('whatsapp', 'whatsapp'), ('email', 'email')], max_length=8)),
            ],
        ),
    ]
