# Generated by Django 2.1.7 on 2020-11-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201103_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_of_followup',
            field=models.DateField(auto_now=True),
        ),
    ]
